#!/usr/bin/python3
"""





#####################################################################
    

                        DO NOT EDIT THIS FILE


#####################################################################






"""
import unittest
from main import caesar_cipher
class Tests(unittest.TestCase):
    def test(self):
        self.assertEqual(caesar_cipher("abcdefghijklmnopqrstuvwxyz"),"defghijklmnopqrstuvwxyzabc")

        
if __name__=='__main__':
    unittest.main()
